version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: >
      sh -c "echo '<h1>Hello from Tailscale Server!</h1><p>Server: basic-tailscale-server</p><p>Deployed via Terraform + Docker Compose</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"